### ISSUE TITLE
supplemental files  in path "/gquadruplex" can not download.

### ISSUE THREAD

**Issue by tanyongjun0815** [ReddyLab/CRADLE#50]
Hello, I want to use your software in identify enhancers in human cell lines, but two supplemental files (gquad_hg19_minus_strand and gquad_hg19_plus_strand) can not download. Are they be moved to another place? Could you kindly provide these two files for me? thank  you very much!

**Comment by Young-Sook** [comment]
Hi,

Sorry for the inconvenience. I just uploaded gquadruplex files on synapse again (syn20369496) and I could download those files. Let me know if you still have a problem. 

Thanks,
Young-Sook

**Comment by tanyongjun0815** [comment]
Hi,
I have successfully download these two files, thanks for your help!

Tan, Yongjun

**Comment by tanyongjun0815** [comment]
Hi,
	Thanks for your help. I successfully run the CRADLE using my data with covariates download from the synapse . But I have an other question: When I identify enhancers and silencer genome-wide with CRADLE, no peaks were identified on chromosome X and chromosome Y. Did this phenomenon caused by low coverage on chromosome X and chromosome Y? When I identify enhancers on each chromosome individually, comparable number of enhancer and silencers were identified on chromosome X and chromosome Y. However, no or little number of silencer and enhancer were identified on some chromosome . Did this phenomenon caused by different thresholds applied on each chromosome? If I want to identify enhancers on all chromosomes, the best choice for me was to perform peak calling on chromosome 1-22 and then calling peaks on chromosome X and Y individually?
 
Thanks, 
Yongjun.

发送自 Windows 10 版邮件应用

发件人: Young-Sook
发送时间: 2021年5月27日 22:17
收件人: ReddyLab/CRADLE
抄送: TanYongjun; Author
主题: Re: [ReddyLab/CRADLE] supplemental files in path "/gquadruplex" cannot download. (#50)

Hi,
Sorry for the inconvenience. I just uploaded gquadruplex files on synapse again (syn20369496) and I could download those files. Let me know if you still have a problem.
Thanks,
Young-Sook

**Comment by Young-Sook** [comment]
Hi,

If the coverage in chrX and chrY is significantly lower than the other chromosomes, it is possible that no peaks are called in those chromosomes. CRADLE applies the same threshold for every chromosome, but that threshold changes depending on the data. CRADLE callPeak subcommand uses the overall variance filter, and tests ten different thresholds which ranges 0-90 percentile of the overall variance in the data, with 10 percentile interval, and select one threshold that outputs the most number of peaks. 

Let's assume you have significantly small coverage in chrX compared to the other chromosomes. This means the genomic regions in chrX would have small overall variances.  If you call peaks only in chrX, the selected threshold should be smaller than the threshold that would have been chosen when CRADLE was applied to whole genome. Because of the smaller threshold, you can detect more peaks in chrX when you call peaks only in chrX. 

Generally, I wouldn't recommend running CRADLE separately for autosomal chromosomes and sex chromosomes unless you have a strong reason to do so, because this could result in applying different thresholds to the same data. Instead, I would recommend increasing your target FDR, but the choice is up to you. You can choose what makes most sense in your data.

Thanks,
Young-sook
