### ISSUE TITLE
hdf files

### ISSUE THREAD

**Issue by netwchao** [ReddyLab/CRADLE#51]
Dear developer:
In my data, The fragment length is 300bp, the length of sequenced reads is 150bp. However, in SYNAPSE, there is not "hg38_fragLen300_kmer150", how can I get or generate "hg38_fragLen300_kmer150" file?
@timreddy @Young-Sook

**Comment by Young-Sook** [comment]
Hi,

If there is no covariate file (.hdf) that matches with your data, I'd recommend using correctBias subcommand instead of correctBias_stored subcommand. To run correctBias subcommand, you need to have mappability file for 150mer, though. 

If you don't have mappability file for 150mer, I'd recommend using hg38_fragLen300_kmer100 hdf files with  correctBias_stored subcommand. We haven't tested how much the fit of the model is sensitive to different parameters such as kmer length, but I believe hg38_fragLen300_kmer100 will still provide pretty reasonable fit. 

In terms of runnning time, correctBias subcommand takes longer time than correctBias_stored subcommand as written in README file. The running time of correctBias subcommand is still reasonable, unless the data is not whole genome. 

Let me know if you have any more question! 

Thanks,
Young-Sook

**Comment by netwchao** [comment]
> Hi,
> 
> If there is no covariate file (.hdf) that matches with your data, I'd recommend using `correctBias` subcommand instead of `correctBias_stored` subcommand. To run `correctBias` subcommand, you need to have mappability file for 150mer, though.
> 
> If you don't have mappability file for 150mer, I'd recommend using hg38_fragLen300_kmer100 hdf files with `correctBias_stored` subcommand. We haven't tested how much the fit of the model is sensitive to different parameters such as kmer length, but I believe hg38_fragLen300_kmer100 will still provide pretty reasonable fit. Another option is not correcting mappability bias. You can choose the type of biases you want to correct with `-biasType` parameter in `correctBias_stored` subcommand.
> 
> In terms of runnning time, `correctBias` subcommand takes longer time than `correctBias_stored` subcommand as written in README file. However, the running time of `correctBias` subcommand is still reasonable unless the data is not whole genome.
> 
> Let me know if you have any more question!
> 
> Thanks,
> Young-Sook

### Thank you very much for your answer.
I will try to analyze my data according to your suggestions.
