### ISSUE TITLE
callPeak.py:185: RuntimeWarning: divide by zero encountered in double_scalars

### ISSUE THREAD

**Issue by netwchao** [ReddyLab/CRADLE#92]
Hi, When I run the “cradle callPeak” command to find the location of the peak， It works fine, but I encountered the warning shown in the picture below：

<img width="1095" alt="e2bdc7a438f4346cb838274e2b43b91" src="https://user-images.githubusercontent.com/56786669/147542961-c006d35a-60fb-403e-a56b-ee39f747fdfc.png">

I can‘t solve this error， Can you please help me with this?
@Young-Sook @tncowart

**Comment by tncowart** [comment]
@netwchao Can you show us what command you use to run callPeak is?

**Comment by tncowart** [comment]
The code that crashes is the line `cohenD = (expRC_mean - ctrlRC_mean) / s` in this function:
```python
def calculateCohenD(ctrlRC, expRC):
	dof = vari.CTRLBW_NUM + vari.EXPBW_NUM - 2

	ctrlRC_mean = np.mean(ctrlRC)
	expRC_mean = np.mean(expRC)

	s = np.sqrt( (  (vari.CTRLBW_NUM-1)*np.power(np.std(ctrlRC, ddof=1), 2) + (vari.EXPBW_NUM-1)*np.power(np.std(expRC, ddof=1), 2)  ) / dof )

	cohenD = (expRC_mean - ctrlRC_mean) / s

	return cohenD
```

`s` is 0 here. So either 
1) `vari.CTRLBW_NUM-1` and `vari.EXPBW_NUM-1` are both 0 
or 
2) `np.std(ctrlRC, ddof=1)` and `np.std(expRC, ddof=1)` are both 0


I'm guessing it's not (1) because then `dof` would be 0 and the divide by `dof` would have failed. So maybe it's (2). But I can't confirm without looking at the data. I'm not sure what it means for a standard deviation to be 0  -- maybe there is only one value in the data?

**Comment by Young-Sook** [comment]
@netwchao Did you have one sample either for `-ctrlbw`or `-expbw` argument? If not, that error could also happen when all replicates have the same read count so that there is no variance between replicates.

**Comment by netwchao** [comment]
@Young-Sook @tncowart Dear developers, thanks for your reply.
the command I use for Call-peak is as follows
```
for chrom in `seq 1 22` X Y ;
do
        cradle callPeak -ctrlbw ${library}293T-inputA-chr${chrom}_corrected.bw ${library}293T-inputB-chr${chrom}_corrected.bw \
                        -expbw ${library}outputA.last-chr${chrom}_corrected.bw ${library}outputB.last-chr${chrom}_corrected.bw \
                        -r ${starr}target/chr${chrom}.target.bed \
                        -fdr 0.05 \
                        -p 15 \
                        -o peakCalling_result/chr${chrom}_peak
done
```
I have two different output libraries， but input libraries A and B are the same. 
I think cohenD does not affect me to identify the element position，when I change command “cohenD = (expRC_mean - ctrlRC_mean) / s” to command “cohenD = (expRC_mean - ctrlRC_mean) / (s+0.000001)”, it works normally，But there are very few peaks called by each chromosome, and all peaks are 50bp in length, I think this is a bit abnormal.

Another question, the sample script you provide has repeated sample input, Does the software support call-peak without repeated samples?  Like Macs2，because there are a lot of peaks identified without repeated input. and from IGV, we can see that the identified location is reasonable.

**Comment by tncowart** [comment]
@Young-Sook I was thinking I could add some code like 
```python
if s == 0:
	print("""
	Warning: Pooled Std Dev of Cohen's D is 0.
	  This could mean that all your read counts are the same or that you
	  aren't using enough BigWig files (You need at least 3).
	""")
	return 0
```

To `calculateCohenD` for the case where `s` is 0. Do you think that's okay?

**Comment by Young-Sook** [comment]
@netwchao Hi Wangchao, 

Sorry for the delay to respond to your question. 

If the two replicates of input are the same, the cohenD should be all `Nan` as we cannot estimate variance between replicates. CohenD is somewhat similar to z statistics so I personally think adding a small number (like 0.000001) wouldn't make much sense. 

When variance across replicates cannot be estimated—either in control library or experimental library, CRADLE calls peaks in a very stringent manner (https://github.com/ReddyLab/CRADLE/blob/main/CRADLE/CallPeak/calculateRC.pyx#L477). This is to decrease the number of false positives when variance estimate is unavailable because we don't know how much credibility that data point has. 

CRADLE uses 50bp window size as default and it adjusts the size if there is a long string of nan values in the data. You can use smaller or bigger window size with using `-wbin`.

CRADLE does call peaks even there is no replicate. However, as mentioned earlier, CRADLE calls peaks in a stringent manner to decrease the number of false positives. Take a look at https://github.com/ReddyLab/CRADLE/blob/main/CRADLE/CallPeak/calculateRC.pyx#L449. 

Let me know if you have any further questions!

Young-Sook

**Comment by Young-Sook** [comment]
@tncowart 
Hi Thomas, 

Sorry for the delay. 

I do like the error message but the return value should be `np.nan` in that case. CohenD is similar to z-statistics, and `cohenD=np.nan` and `cohenD=0` have totally different meaning. 

I think you can add the error message here:
https://github.com/ReddyLab/CRADLE/blob/main/CRADLE/CallPeak/callPeak.py#L189. 

It would be helpful to print out the coordinate of the region as well by tossing `regionChromo`, `regionStart` and `regionEnd ` here: https://github.com/ReddyLab/CRADLE/blob/main/CRADLE/CallPeak/callPeak.py#L51

Thanks,
Young-Sook

**Comment by tncowart** [comment]
Addressed in https://github.com/ReddyLab/CRADLE/pull/93

**Comment by netwchao** [comment]
@Young-Sook @tncowart   HI,
Thank you for your reply, I have a clear understanding of the whole principle. Thank you for developing this software, I think it is helpful for my research, I wish you a happy life and smooth work.
Thanks,
Wangchao

**Comment by tncowart** [comment]
@netwchao You're welcome! Take care.
